# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

addons:
  postgresql: "9.4"

notifications:
  email: false

sudo: false

language: python

cache:
  - pip

services:
  - mysql
  - postgresql

env:
  global:
    - ES2_DOWNLOAD_URL="https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/2.2.0/elasticsearch-2.2.0.tar.gz"
    - ES5_DOWNLOAD_URL="https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.6.4.tar.gz"
    - ES6_DOWNLOAD_URL="https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.2.0.tar.gz"
  matrix:
  - REQUIREMENTS=lowest EXTRAS=all,sqlite,elasticsearch2 SQLALCHEMY_DATABASE_URI="sqlite:///test.db" ES_URL=$ES2_DOWNLOAD_URL
  - REQUIREMENTS=lowest EXTRAS=all,mysql,elasticsearch5 SQLALCHEMY_DATABASE_URI="mysql+pymysql://travis@localhost:3306/invenio" ES_URL=$ES5_DOWNLOAD_URL
  - REQUIREMENTS=lowest EXTRAS=all,postgresql,elasticsearch6 SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio" ES_URL=$ES6_DOWNLOAD_URL
  - REQUIREMENTS=release EXTRAS=all,sqlite,elasticsearch2 SQLALCHEMY_DATABASE_URI="sqlite:///test.db" ES_URL=$ES2_DOWNLOAD_URL
  - REQUIREMENTS=release EXTRAS=all,mysql,elasticsearch5 SQLALCHEMY_DATABASE_URI="mysql+pymysql://travis@localhost:3306/invenio" ES_URL=$ES5_DOWNLOAD_URL
  - REQUIREMENTS=release E2E_WEBDRIVER_BROWSERS="Firefox" EXTRAS=all,postgresql,elasticsearch6 SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio" ES_URL=$ES6_DOWNLOAD_URL
  - REQUIREMENTS=devel EXTRAS=all,sqlite,elasticsearch2 SQLALCHEMY_DATABASE_URI="sqlite:///test.db" ES_URL=$ES2_DOWNLOAD_URL
  - REQUIREMENTS=devel EXTRAS=all,mysql,elasticsearch5 SQLALCHEMY_DATABASE_URI="mysql+pymysql://travis@localhost:3306/invenio" ES_URL=$ES5_DOWNLOAD_URL
  - REQUIREMENTS=devel EXTRAS=all,postgresql,elasticsearch6 SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio" ES_URL=$ES6_DOWNLOAD_URL


python:
  - "2.7"
  - "3.5"

before_install:
  - "mkdir /tmp/elasticsearch"
  - "wget -O - $ES_URL | tar xz --directory=/tmp/elasticsearch --strip-components=1"
  - "if [ ${ES_URL} == ${ES2_DOWNLOAD_URL} ]; then /tmp/elasticsearch/bin/plugin install -b mapper-attachments; fi"
  - "/tmp/elasticsearch/bin/elasticsearch > /tmp/local-es.log &"
  - "travis_retry pip install --upgrade pip setuptools py"
  - "travis_retry pip install twine wheel coveralls requirements-builder"
  - "requirements-builder --level=min setup.py > .travis-lowest-requirements.txt"
  - "requirements-builder --level=pypi setup.py > .travis-release-requirements.txt"
  - "requirements-builder --level=dev --req requirements-devel.txt setup.py > .travis-devel-requirements.txt"

install:
  - "travis_retry pip install -r .travis-${REQUIREMENTS}-requirements.txt"
  - "travis_retry pip install -e .[${EXTRAS}]"

script:
  - "./run-tests.sh"

after_success:
  - coveralls

deploy:
  provider: pypi
  user: inveniosoftware
  password:
    secure: "GKo04JqEh4pusFTXsbsfPQZqJGFt+dbVAw6oZRXqWvCwbPsph5oZMr5SmMvd03Yf89jV8aSwq0M0LMxRTmirNGieizPH9V8MPnublNZE+DlALDRzJOW8A7LljwtikoURWQ292TQUMbl18+s/qy3dSiiI4NWrhIsYNS/yhLNI4Y5pbstTSoBSHB5+taXo7uDcXUDs9k9kaz10ljGMdvNx7KSvIp2XVNKFn68TXt8UEpPCjT4ACrco2Hwx9jJBxL0pXNE+m6gSVb1zpHPzcCQ/tI9VyWiz/edvzLRIu+qNDM6U1n9QNmoOXBwXVQWDbAvy2qE7nUJTUiH0r295LVJRcBg52cO1cHnHcYmoG0jkg6CDnT5yq1DxmLg77U/xCgYY028QmqtkjEOSaWB2zCrMS4cJYiCG77GP8GPqUbpL/NnGRgjPxD+9Cxq0FYU56wmZ6xRQj1lm+fRefiHe6fkIcxq8AbH/AEpcO9oaeXUTDrPRQBfZWN9wk9BVqgpsYtUlrY6OxhFu6BBQDk8BB8AF8LBMyDyRurg302PXtfxHGpUxfwSORxd0/rYowIdPwMGVE8lpdchb0RVqtbKWv07PrMqyO/MxsZDv56PAijMJhwmOqgmu4jD2AJM1GfE9587sFS3C+La9YX4VbRSbPTW1+xwr67W+4vie+dtIJx5fa6Q="
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    python: "2.7"
    condition: $REQUIREMENTS = release
